// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FButton: typeof import('@/shared/ui/FButton')['FButton']
    FCard: typeof import('@/shared/ui/FCard')['FCard']
    FCardsGrid: typeof import('@/shared/ui/FCardsGrid')['FCardsGrid']
    FContainer: typeof import('@/shared/ui/FContainer')['FContainer']
    HListbox: typeof import('@headlessui/vue')['Listbox']
    HListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    HListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    HListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
  }
}
